
export const LOAD_POSTS_REQUEST = 'LOAD_POSTS_REQUEST'
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS'
export const LOAD_POSTS_BY_CATEGORY = 'LOAD_POSTS_BY_CATEGORY'
export const TOGGLE_VOTE_SCORE = 'TOGGLE_VOTE_SCORE'
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES'
export const LOAD_POSTS_BY_ID = 'LOAD_POSTS_BY_ID'
export const LOAD_COMMENTS_BY_POST_ID = 'LOAD_COMMENTS_BY_POST_ID'
export const TOGGLE_VOTE_SCORE_COMMENTS = 'TOGGLE_VOTE_SCORE_COMMENTS'
export const TOGGLE_VOTE_SCORE_POST_ITEM = 'TOGGLE_VOTE_SCORE_POST_ITEM'
export const SAVE_COMMENT = 'SAVE_COMMENT'
export const UPDATE_COMMENT_COUNT = 'UPDATE_COMMENT_COUNT'
export const DELETE_POST = 'DELETE_POST'
export const EDIT_POST = 'EDIT_POST'
export const ADD_POST = 'ADD_POST'





