
export const GET_LIST_OF_CATEGORIES = 'GET_LIST_OF_CATEGORIES'
export const GET_ALL_OF_POSTS = 'GET_ALL_OF_POSTS'
export const DELETE_POST = 'DELETE_POST'
export const EDIT_POST = 'EDIT_POST'
export const ADD_POST = 'ADD_POST'
export const INCREASE_VOTE = 'INCREASE_VOTE'
export const DECREASE_VOTE = 'DECREASE_VOTE'
